#!/usr/bin/env bash
# =============================================================================
#  ZSH Setup — Oh My Zsh + Powerlevel10k + best plugins
# =============================================================================
set -euo pipefail

HOMEBREW_PREFIX="$(brew --prefix)"

# ── Oh My Zsh ─────────────────────────────────────────────────────────────────
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  echo "  ➜  Installing Oh My Zsh..."
  RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
  echo "  ✔  Oh My Zsh already installed"
fi

ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"

# ── Plugins ───────────────────────────────────────────────────────────────────
install_omz_plugin() {
  local name="$1" repo="$2"
  if [[ ! -d "$ZSH_CUSTOM/plugins/$name" ]]; then
    echo "  ➜  Installing plugin: $name"
    git clone --depth=1 "$repo" "$ZSH_CUSTOM/plugins/$name"
  else
    echo "  ✔  Plugin already installed: $name"
  fi
}

install_omz_plugin "zsh-autosuggestions"    "https://github.com/zsh-users/zsh-autosuggestions"
install_omz_plugin "zsh-syntax-highlighting" "https://github.com/zsh-users/zsh-syntax-highlighting"
install_omz_plugin "zsh-completions"         "https://github.com/zsh-users/zsh-completions"
install_omz_plugin "zsh-history-substring-search" "https://github.com/zsh-users/zsh-history-substring-search"

# ── Starship Prompt ───────────────────────────────────────────────────────────
if ! command -v starship &>/dev/null; then
  echo "  ➜  Installing Starship prompt..."
  curl -sS https://starship.rs/install.sh | sh -s -- --yes
fi

# ── Starship Config ───────────────────────────────────────────────────────────
mkdir -p "$HOME/.config"
cat > "$HOME/.config/starship.toml" << 'STARSHIP'
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$python\
$java\
$kotlin\
$aws\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](bg:#1d2230)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[java]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[kotlin]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[aws]
symbol = "☁️"
style = "bg:#212736"
format = '[[ $symbol ($profile)(\($region\)) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
STARSHIP

echo "  ✔  Starship config written"

# ── Nerd Font ─────────────────────────────────────────────────────────────────
echo "  ➜  Installing JetBrains Mono Nerd Font..."
brew install --cask font-jetbrains-mono-nerd-font 2>/dev/null || true

# ── .zshrc ────────────────────────────────────────────────────────────────────
echo "  ➜  Writing ~/.zshrc..."

cat > "$HOME/.zshrc" << 'ZSHRC'
# =============================================================================
#  ~/.zshrc — Generated by mac-setup 🚀
# =============================================================================

# ── Oh My Zsh ─────────────────────────────────────────────────────────────────
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""   # Using Starship instead

plugins=(
  git
  gh
  docker
  docker-compose
  aws
  python
  pip
  pyenv
  node
  npm
  gradle
  mvn
  vscode
  macos
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-completions
  zsh-history-substring-search
  fzf
  sudo          # press ESC twice to add sudo to last command
  copypath      # copy current path to clipboard
  copyfile      # copy file contents to clipboard
  web-search    # 'google something' from terminal
  z             # jump to frecent dirs
)

source "$ZSH/oh-my-zsh.sh"

# ── Homebrew ──────────────────────────────────────────────────────────────────
if [[ -f /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -f /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

# ── Starship Prompt ───────────────────────────────────────────────────────────
eval "$(starship init zsh)"

# ── PATH ──────────────────────────────────────────────────────────────────────
export PATH="$HOME/.local/bin:$HOME/bin:/usr/local/bin:$PATH"
export PATH="$(brew --prefix)/opt/openjdk@21/bin:$PATH"

# ── Java / Kotlin ─────────────────────────────────────────────────────────────
export JAVA_HOME="$(brew --prefix openjdk@21 2>/dev/null)/libexec/openjdk.jdk/Contents/Home"

# ── pyenv ─────────────────────────────────────────────────────────────────────
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# ── nvm ───────────────────────────────────────────────────────────────────────
export NVM_DIR="$HOME/.nvm"
[ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && source "$(brew --prefix)/opt/nvm/nvm.sh"
[ -s "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm" ] && source "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm"

# ── zoxide (smarter cd) ───────────────────────────────────────────────────────
eval "$(zoxide init zsh)"

# ── fzf ───────────────────────────────────────────────────────────────────────
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

# ── History ───────────────────────────────────────────────────────────────────
HISTSIZE=50000
SAVEHIST=50000
HISTFILE=~/.zsh_history
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY

# ── Aliases — Navigation ──────────────────────────────────────────────────────
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ~='cd ~'
alias -- -='cd -'

# ── Aliases — ls / eza ────────────────────────────────────────────────────────
alias ls='eza --icons --group-directories-first'
alias ll='eza -alh --icons --group-directories-first'
alias lt='eza --tree --icons --level=2'
alias la='eza -a --icons'

# ── Aliases — Git ─────────────────────────────────────────────────────────────
alias g='git'
alias gs='git status'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit -m'
alias gca='git commit --amend'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpl='git pull'
alias gl='git log --oneline --graph --decorate --all'
alias gd='git diff'
alias gds='git diff --staged'
alias gst='git stash'
alias gstp='git stash pop'
alias gbr='git branch'
alias gbrd='git branch -d'

# ── Aliases — Docker ──────────────────────────────────────────────────────────
alias d='docker'
alias dc='docker compose'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias drm='docker rm $(docker ps -aq)'
alias drmi='docker rmi $(docker images -q)'
alias dprune='docker system prune -af'

# ── Aliases — Python ──────────────────────────────────────────────────────────
alias py='python3'
alias pip='pip3'
alias venv='python3 -m venv .venv && source .venv/bin/activate'
alias activate='source .venv/bin/activate'

# ── Aliases — AWS ─────────────────────────────────────────────────────────────
alias awsp='export AWS_PROFILE=$(aws configure list-profiles | fzf)'
alias awsw='aws sts get-caller-identity'

# ── Aliases — Misc ────────────────────────────────────────────────────────────
alias cat='bat --style=auto'
alias grep='grep --color=auto'
alias mkdir='mkdir -pv'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias df='df -h'
alias du='du -sh'
alias ports='lsof -i -P -n | grep LISTEN'
alias myip='curl -s https://ipinfo.io/ip'
alias reload='source ~/.zshrc && echo "✔ .zshrc reloaded"'
alias zshconfig='${EDITOR:-code} ~/.zshrc'
alias path='echo $PATH | tr ":" "\n" | nl'
alias flushdns='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'

# ── Aliases — Claude Code ─────────────────────────────────────────────────────
alias cc='claude'
alias ccc='claude --continue'

# ── Functions ─────────────────────────────────────────────────────────────────

# mkcd: make directory and cd into it
mkcd() { mkdir -p "$@" && cd "$_"; }

# extract: universal archive extractor
extract() {
  if [ -f "$1" ]; then
    case "$1" in
      *.tar.bz2)  tar xjf "$1"  ;;
      *.tar.gz)   tar xzf "$1"  ;;
      *.tar.xz)   tar xJf "$1"  ;;
      *.bz2)      bunzip2 "$1"  ;;
      *.gz)       gunzip "$1"   ;;
      *.tar)      tar xf "$1"   ;;
      *.tbz2)     tar xjf "$1"  ;;
      *.tgz)      tar xzf "$1"  ;;
      *.zip)      unzip "$1"    ;;
      *.Z)        uncompress "$1" ;;
      *.7z)       7z x "$1"    ;;
      *)          echo "'$1' cannot be extracted" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# port: show what's on a port
port() { lsof -i ":${1}" | grep LISTEN; }

# killport: kill process on a port
killport() { lsof -ti ":${1}" | xargs kill -9; }

# weather: show weather
weather() { curl -s "wttr.in/${1:-}?format=3"; }

# newpr: open new GitHub PR in browser
newpr() { gh pr create --web; }

# jdk: switch Java version
jdk() {
  local version=$1
  export JAVA_HOME=$(/usr/libexec/java_home -v "$version")
  java -version
}

# ── Editor ────────────────────────────────────────────────────────────────────
export EDITOR='code --wait'
export VISUAL="$EDITOR"

# ── Auto-completions ──────────────────────────────────────────────────────────
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# ── Key Bindings ──────────────────────────────────────────────────────────────
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey "^[[1;5C" forward-word   # Ctrl+Right
bindkey "^[[1;5D" backward-word  # Ctrl+Left

# ── Local overrides ───────────────────────────────────────────────────────────
[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"
ZSHRC

echo "  ✔  ~/.zshrc written"

# ── .zprofile ─────────────────────────────────────────────────────────────────
# Needed so pyenv shims are on PATH for non-interactive (login) shells / scripts
echo "  ➜  Writing ~/.zprofile..."
cat > "$HOME/.zprofile" << 'ZPROFILE'
# pyenv — must be in .zprofile so shims are available in non-interactive shells
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
ZPROFILE
echo "  ✔  ~/.zprofile written"

# Set zsh as default shell
if [[ "$SHELL" != "$(which zsh)" ]]; then
  echo "  ➜  Setting ZSH as default shell..."
  chsh -s "$(which zsh)" || true
fi

echo "  ✔  ZSH setup complete"
